#! /bin/bash
#Con este Script instalamos wordpress
#Normalmente se ejecuta con "InstalarServidorBasico"

	#Descargamos wordpress, lo copiamos y borramos el temporal
	clear
	echo "Ruta para instalar Wordpress, no introducir nada si se desea la ruta de por defecto (/var/www/html/)"
	read rutaWordpress
	if [ "$rutaWordpress" = "" ]; then
	rutaWordpress="/var/www/html"
	sudo mkdir /var/www/html
	fi
	
	#Descargamos Wordpress
	wget http://wordpress.org/latest.tar.gz
	tar -xzf latest.tar.gz
	cp -r wordpress/* $rutaWordpress
	rm -r wordpress
	rm -r latest.tar.gz
	clear
	
	#Preguntamos datos para la base de datos de wordpress
	echo "Nombre de la base de datos para wordpress"
	read wordpressDB
	echo "Usuario Mysql para wordpress"
	read wordpressUser
	echo "Contraseña para el usuario wordpress mysql"
	read -s wordpressPass 
	
	#Creamos las tablas necesarias
	mysql -uroot -pasdfasdf -e "create database $wordpressDB"
	mysql -uroot -pasdfasdf -e "CREATE USER $wordpressUser"
	mysql -uroot -pasdfasdf -e "SET PASSWORD FOR $wordpressUser= PASSWORD('$wordpressPass')"
	mysql -uroot -pasdfasdf -e "GRANT ALL PRIVILEGES ON $wordpressDB.* TO $wordpressUser IDENTIFIED BY '$wordpressPass'"
	
	#creamos wp-config
	#archivo de configuracion de wordpress
	cp $rutaWordpress/wp-config-sample.php $rutaWordpress/wp-config.php

	#Ponemos los datos de la bd para wordpress en wp-config
	perl -pi -e "s/database_name_here/$wordpressDB/g" $rutaWordpress/wp-config.php
	perl -pi -e "s/username_here/$wordpressUser/g" $rutaWordpress/wp-config.php
	perl -pi -e "s/password_here/$wordpressPass/g" $rutaWordpress/wp-config.php
	
	#Creamos la carpeta uploads y le agregamos permisos para poner pluggins
	mkdir $rutaWordpress/wp-content/uploads
	chmod 777 $rutaWordpress/wp-content/uploads

     #Reinicimos Servicios
     /etc/init.d/./apache2 restart
	/etc/init.d/./vsftpd restart 

	#Una vez creada la base de datos abrimos firefox para configurar 
	xdg-open http://localhost/


